version: "3"
services:
  db:
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: hackthecat
    restart: always
  web:
    build: ./web
#    environment:
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: on-failure